services:
  php-cli:
   container_name: php-cli
   environment:
     REDIS_HOST: 'redis'
     LOG_PATH: '/app/log/leads.txt'
   build:
     dockerfile: docker/php-cli/Dockerfile
   volumes:
     - ./log:/app/log/

  redis:
    image: redis:7.4
    container_name: redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge

volumes:
    redis: